export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as Header } from './Header'
export { default as ActionButton } from './Button/ActionButton'
export { default as MobileMenu } from './MobileMenu'
export { default as Banner } from './Banner'
export { default as FeaturesBlocks } from './FeaturesBlocks'
export { default as ModalVideo } from './ModalVideo'
// export { default as Features } from './Features'
export { default as Testimonials } from './Testimonials'
export { default as Newsletter } from './Newsletter'
